export { ColorProperty } from './ColorProperty';
export { FractionProperty } from './FractionProperty';
export { InterpolatorProperty } from './InterpolatorProperty';
export { NameProperty } from './NameProperty';
export { NumberProperty } from './NumberProperty';
export { PathProperty } from './PathProperty';
export { Property } from './Property';
export type { Animatable, Inspectable } from './PropertyMaps';
export { EnumProperty } from './EnumProperty';
export type { Option } from './EnumProperty';
